import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "doc",
      id: "installation",
      label: "Installation",
    },
    {
      type: "doc",
      id: "configuration",
      label: "Configuration",
    },
    {
      type: "category",
      label: "Core (@mjfy/core)",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Core Engine",
        description: "The logic layer for your MUI-based forms.",
      },
      items: [{ type: "autogenerated", dirName: "core" }],
    },
    {
      type: "category",
      label: "@mjfy/form-builder",
      collapsed: false,
      link: {
        type: "doc",
        id: "form-builder/overview", // Link directly to the main builder doc
      },
      items: [{ type: "autogenerated", dirName: "form-builder" }],
    },
  ],
};

export default sidebars;
